// <auto-generated />
using System;
using InvoicesManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvoiceManagementSystem.Migrations
{
    [DbContext(typeof(InvoiceManagementContext))]
    [Migration("20210204224604_SeedLocatii")]
    partial class SeedLocatii
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("InvoicesManagementSystem.Entities.DetaliiFactura", b =>
                {
                    b.Property<int>("IdDetaliiFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Valoare")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdDetaliiFactura", "IdLocatie");

                    b.HasIndex("IdLocatie");

                    b.HasIndex("IdFactura", "IdLocatie");

                    b.ToTable("DetaliiFacturi");
                });

            modelBuilder.Entity("InvoicesManagementSystem.Entities.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumarFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFactura", "IdLocatie");

                    b.HasIndex("IdLocatie");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("InvoicesManagementSystem.Entities.Locatie", b =>
                {
                    b.Property<int>("IdLocatie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocatie");

                    b.ToTable("Locatii");

                    b.HasData(
                        new
                        {
                            IdLocatie = 1,
                            Adresa = "Strada Muresenilor",
                            Nume = "Brasov"
                        },
                        new
                        {
                            IdLocatie = 2,
                            Adresa = "Strada Balcescu",
                            Nume = "Bucuresti"
                        });
                });

            modelBuilder.Entity("InvoicesManagementSystem.Entities.DetaliiFactura", b =>
                {
                    b.HasOne("InvoicesManagementSystem.Entities.Locatie", "Locatie")
                        .WithMany("DetaliiFacturi")
                        .HasForeignKey("IdLocatie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoicesManagementSystem.Entities.Factura", "Factura")
                        .WithMany("DetaliiFactura")
                        .HasForeignKey("IdFactura", "IdLocatie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("InvoicesManagementSystem.Entities.Factura", b =>
                {
                    b.HasOne("InvoicesManagementSystem.Entities.Locatie", "Locatie")
                        .WithMany("Facturi")
                        .HasForeignKey("IdLocatie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("InvoicesManagementSystem.Entities.Factura", b =>
                {
                    b.Navigation("DetaliiFactura");
                });

            modelBuilder.Entity("InvoicesManagementSystem.Entities.Locatie", b =>
                {
                    b.Navigation("DetaliiFacturi");

                    b.Navigation("Facturi");
                });
#pragma warning restore 612, 618
        }
    }
}
